version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: your_laravel_app_image
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    networks:
      - laravel
    
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql-data:
